bert_path: pretrained_models/chinese-roberta-wwm-ext-large
cnhubert_base_path: pretrained_models/chinese-hubert-base
default_speaker: sanyueqi
device: cpu
hz: 32000
is_half: true
keep_wav: false
open_browser: false
play: false
public: true
server_host: 0.0.0.0
server_port: 8080
speaker:
  sanyueqi:
    gpt_path: models/Nana7mi/Nana7mi-e21.ckpt
    ref_wav_path: audio/Nana7mi/Nana7mi_20.wav
    sovits_path: models/Nana7mi/Nana7mi_e47_s2444.pth
    text: 怎么点不开你得私信列表啊
    text_lang: zh
tmp_dir: ./TEMP
